# CAP Project - HTTP Test File
# Use with REST Client extension in VS Code

//product
//GET http://localhost:4004/odata/v4/productshop/product

//Supplier
GET http://localhost:4004/odata/v4/productshop/Supplier
